### ISSUE TITLE
Issue in logging and registering

### ISSUE THREAD

**Issue by manish4990** [nvisium-jack-mannino/OWASP-GoatDroid-Project#1]
Hi All,

Need Help to set up Goatdroid environment.
I tried to install new version of goatdroid.

in destination info i provided my system IP address and HTTPS port: port mentioned in goatdroid gui  and in goatdroid GUI configuration i provided Host: my ip address, and proxy port 8888.

i have tried changing the port: to 8080, 8888, 9888 but nothing worked out.

While Registering i got black box without any message. and some times it could not connect with remote server.

please let me know how to proceed.

Regards,
Manish

**Comment by manish4990** [comment]
Hi All,

Is there anyone who is working with goatdroid.
I am getting again the could not contact the remote service.

Any Help? 
 Regards,
Manish

**Comment by nvisium-jack-mannino** [comment]
Within the GUI, did you start the web service? Please confirm that the service is started. It doesn't start automatically when the GUI is open, but rather must be started manually by clicking the "Start Web Service" button.

**Comment by manish4990** [comment]
Yes i have started the web service manually.

**Comment by manish4990** [comment]
I have sent you the mail at your email id: Jack@nvisiumsecurity.com with configuration screen shots.
Just check if my configuration ports is okay.
i am little confused which port to use where?

**Comment by manish4990** [comment]
Any updates on this ....

**Comment by manish4990** [comment]
Any Updates ?
