### ISSUE TITLE
App opens with 'Hello world'

### ISSUE THREAD

**Issue by nap-francois** [nvisium-jack-mannino/OWASP-GoatDroid-Project#17]
I am a software tester, with an Android developer we tried to launch the app using IntelliJ and Android Studios  but the only module we could specify was 'app', which was resulting in having the app launched displaying 'hello world' which is the default app screen. We haven't found any file to launch the 2 proper applications, are we missing something?

**Comment by nvisium-jack-mannino** [comment]
Work from the 'old' branch. I (stupidly) wanted to overhaul the project but started working from Master.

https://github.com/jackMannino/OWASP-GoatDroid-Project/tree/old
