### ISSUE TITLE
No README in the master branch

### ISSUE THREAD

**Issue by Sx41N** [nvisium-jack-mannino/OWASP-GoatDroid-Project#18]
Could you please put the README file into the master branch? There are addition informaition with the download link to self-contained training environment. I think it will be very useful for everyone, who wants to try out the GoatDroid apps. The README is only available in other branches like "web".

**Comment by scottyab** [comment]
+1

**Comment by ahmadsalah85** [comment]
I have tried to download but once I run it gave me too many errors,,,,please if you have working copy with source code it will help me too much

**Comment by nvisium-jack-mannino** [comment]
Work from the 'old' branch. I (stupidly) wanted to overhaul the project but started working from Master.

https://github.com/jackMannino/OWASP-GoatDroid-Project/tree/old

**Comment by ahmadsalah85** [comment]
I have tried still even the old is not working, please if you can help to provide me with source code for a running copy. It will solve one of the biggest issues in my research I am stuck in finding such open-source app

**Comment by marctmiller** [comment]
@ahmadsalah85, yer gonna hafta reach into that autodidact part of yer brain.

**Comment by ahmadsalah85** [comment]
@marctmiller I did not understand what you mean?
Anyway my problem is I am doing a research about mobile cloud application security and I need one open source application for the matter of testing...
The application I am looking show be on android even if it is not mobile cloud app I will change it to make it mobile cloud app....but until now I could not find any.
If you have such app or you know one please provide me with the link
