### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by vbisbest** [nvisium-jack-mannino/OWASP-GoatDroid-Project#19]
Are there any setup steps?  I dont see the android.jar file (the guy that listens on port 12000).  Only the main menu seems to work, everything under it is just a white screen.  Thanks.

**Comment by nvisium-jack-mannino** [comment]
Work from the 'old' branch. I (stupidly) wanted to overhaul the project but started working from Master.

https://github.com/jackMannino/OWASP-GoatDroid-Project/tree/old
