### ISSUE TITLE
Log into the FourGoats application with username: joegoat password: goatdroid.

### ISSUE THREAD

**Issue by manish4990** [nvisium-jack-mannino/OWASP-GoatDroid-Project#2]
In Goatdroid Gui under Getting started point 5 says that Log into the FourGoats application with username: joegoat password: goatdroid.
But tools->utilities->database browser -> fourgoats -> users
and execute select \* from users

it shows only 5 users:
Handbitter555
goat4life
joehorns1
androidguy93
goatdroid

there is no user called joegoat.

**Comment by nvisium-jack-mannino** [comment]
Try username: goatdroid password: goatdroid.

The joegoat account is not present in the distribution, and the documentation incorrectly references it. The goatdroid account is the default account in both applications. Additionally, all accounts within the user database use 'goatdroid' as their login passwords.

**Comment by manish4990** [comment]
Hi Jack,
I tried with username: goatdroid password: goatdroid it says Login Failed Try again and when i tried to register new one blank black box appears as a message.

**Comment by manish4990** [comment]
Any Updates ?

**Comment by nvisium-jack-mannino** [comment]
Within the FourGoats app itself, did you also set the destination info? At the login page, hit the menu button and enter the IP address of the host where the web service is started and listening.

**Comment by manish4990** [comment]
Yes i have set the destination info as my IP address.. can you please clarify whihc port i have to set as i have tried with different port but didn't worked ...

**Comment by nvisium-jack-mannino** [comment]
It should be port 9888.

Were you able to get this resolved?

**Comment by manish4990** [comment]
Still not able to login or register.
i have started the webservice and set the virtula machine path and sdk path.
then opened the application in the emulator and in Destination info i have set the Host as my local machine IP address and HTTPS port as 9888 an then tried to login anf tried to register .
while registering i got blank small black popup without any message.

**Comment by manish4990** [comment]
When i tried to login with username: goatdroid password: goatdroid. it gives error login failed try again.
And when tried to register it give blank popup as shown below
![Capture](https://f.cloud.github.com/assets/2578587/16600/396b4e14-4840-11e2-94b3-637fcb642b75.PNG)

**Comment by rupeendar** [comment]
Unable to Start ''Start Web services"
