### ISSUE TITLE
goatdroid-gui.jar not found

### ISSUE THREAD

**Issue by EmanueleMatador** [nvisium-jack-mannino/OWASP-GoatDroid-Project#3]
Hi All,

I am trying to install GoatDroid but i do not found the "goatdroid-gui.jar" referenced on GettingStarted page.

Could you please tell me how can i start the application or where i can find that file?

Thanks in advance,

Emanuele

**Comment by chirinosky** [comment]
when you unzip the download file, cd into the location of the folder and launch goatdroid-<version>.jar.  For example:

unzipped file /home/user/training/OWASP-GoatDroid-0.9
cd OWASP-GoatDroid-0.9
java -jar goatdroid-0.9.jar

**Comment by EmanueleMatador** [comment]
Hello Jack,

thank you for your answer.

But...

MacBook-Pro-di-Emanuele:OWASP-GoatDroid-Project-master emanuele$ pwd
/Users/emanuele/Downloads/OWASP-GoatDroid-Project-master
MacBook-Pro-di-Emanuele:OWASP-GoatDroid-Project-master emanuele$ find ./
-name *.jar
.//OWASP GoatDroid- GUI/lib/asm-3.1.jar
.//OWASP GoatDroid- GUI/lib/commons-exec-1.1.jar
.//OWASP GoatDroid- GUI/lib/commons-net-3.0.1.jar
.//OWASP GoatDroid- GUI/lib/derby.jar
.//OWASP GoatDroid- GUI/lib/derbyclient.jar
.//OWASP GoatDroid- GUI/lib/jersey-bundle-1.12.jar
.//OWASP GoatDroid- GUI/lib/jettison-1.1.jar
.//OWASP GoatDroid- GUI/lib/jetty-all-7.4.2.v20110526.jar
.//OWASP GoatDroid- GUI/lib/jsr311-api-1.1.1.jar
.//OWASP GoatDroid- GUI/lib/mysql-connector-java-5.1.16-bin.jar
.//OWASP GoatDroid- GUI/lib/servlet-api-2.5-6.1H.14.1.jar
MacBook-Pro-di-Emanuele:OWASP-GoatDroid-Project-master emanuele$ find ./
-name *.jar | grep goat

There is NOT goatdroid-0.9.jar.

Thank you,

Emanuele

**Comment by nvisium-jack-mannino** [comment]
Ahh, looks like you need to download the .zip that contains the built project. You can grab that here:

https://github.com/jackMannino/OWASP-GoatDroid-Project/downloads

The .jar is in the root directory when you unzip it.

**Comment by EmanueleMatador** [comment]
Lol! thank you :)

**Comment by chirinosky** [comment]
LOL no worries!  Glad I can help.
