### ISSUE TITLE
why I can not find the help document and the lessons folder and top10 folder is empty? 

### ISSUE THREAD

**Issue by 1aoying** [nvisium-jack-mannino/OWASP-GoatDroid-Project#4]
why I can not find the help document and the lessons folder and top10 folder is empty?

**Comment by kworth** [comment]
I'm also having an issue with empty lessons and top10 folders (screenshot attached). Any reason this was closed without any response as to why?

![screen shot 2013-10-10 at 10 43 33 am](https://f.cloud.github.com/assets/407644/1307148/ef128b06-31ba-11e3-826d-250d8c5d4609.png)
