### ISSUE TITLE
Where is the Android source + build instructions?

### ISSUE THREAD

**Issue by jaxley** [nvisium-jack-mannino/OWASP-GoatDroid-Project#5]
Just starting to take a look at GoatDroid but I only see the GUI source, not the Android application source.  Is that accessible in GIT somewhere?

**Comment by nvisium-jack-mannino** [comment]
The Android apps are located within their own branches:

https://github.com/jackMannino/OWASP-GoatDroid-Project/branches

Documentation is light, I'm getting ready to do a fairly large number of
modifications including getting rid of the Swing GUI in favor of a web
application. Also adding better setup and lesson documentation as well as a
PhoneGap application.

On Tue, May 21, 2013 at 8:10 PM, jaxley notifications@github.com wrote:

> Just starting to take a look at GoatDroid but I only see the GUI source,
> not the Android application source. Is that accessible in GIT somewhere?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jackMannino/OWASP-GoatDroid-Project/issues/5
> .

## 

Jack Mannino
nVisium Security
(703) 679-8528
_Jack@nVisiumSecurity.com
https://www.nvisium.com_
