### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by cktricky** [nvisium-jack-mannino/OWASP-GoatDroid-Project#8]
Unless I'm missing something, the getting started section needs to be updated as I am having issues finding the goatdroid.jar

**Comment by nvisium-jack-mannino** [comment]
You're correct, it's the jar in the root directory that has the version at the end. Will update it.

**Comment by cktricky** [comment]
Kk, here is the list of jar files I have

OWASP GoatDroid- FourGoats/lib/android-support-v4.jar
OWASP GoatDroid- Herd Financial/bin/jarlist.cache
OWASP GoatDroid- Herd Financial/libs/commons-codec.jar
OWASP GoatDroid- Herd Financial/libs/guava-r09.jar
OWASP GoatDroid- Herd Financial/libs/sqlcipher.jar
OWASP_GoatDroid_FourGoats_PhoneGap/cordova/appinfo.jar
OWASP_GoatDroid_FourGoats_PhoneGap/libs/cordova-2.9.0.jar
actionbarsherlock/bin/actionbarsherlock.jar
actionbarsherlock/bin/jarlist.cache
actionbarsherlock/libs/android-support-v4.jar

**Comment by nvisium-jack-mannino** [comment]
The jar is in the download, not the source. Supposed to reference the compiled version in the downloadable zip.

**Comment by cktricky** [comment]
![jackmanninoowasp-goatdroid-project](https://f.cloud.github.com/assets/544667/795085/bb737424-ecda-11e2-9b9e-f15ad97f45c1.png)

Using this?

**Comment by cktricky** [comment]
nevermind, found the link on the readme, actually thought they had deprecated that functionality in the latest versions of github.
